### ISSUE TITLE
Adding limit and offset to albums

### ISSUE THREAD

**Issue by ZsemberiDaniel** [adamint/spotify-web-api-kotlin#11]
Currently the ClientLibraryAPI.getSavedAlbums() does not support limit and offset parameters even though the Spotify API clearly supports it. It is an easy fix but for some reason your repository does not want to accept my pushes.

```kotlin
    fun getSavedAlbums(limit: Int? = null, offset: Int? = null, market: Market? = null): SpotifyRestAction<PagingObject<SavedAlbum>> {
        return toAction(Supplier {
            get(EndpointBuilder("/me/albums").with("limit", limit).with("offset", offset).with("market", market)
                    .build()).toPagingObject<SavedAlbum>(endpoint = this)
        })
    }
```

**Comment by adamint** [comment]
Thanks for bringing that up! If you create a pull request, I can review and merge it into the master branch

**Comment by ZsemberiDaniel** [comment]
Sorry, like I said I created a branch for it and tried to push it there so I can create a pull request but for some reason it says that permission for ZsemebriDaniel denied.

**Comment by ZsemberiDaniel** [comment]
Ah thanks! I have not done this before so I assumed that was the way to do it.
