### ISSUE TITLE
Http proxy

### ISSUE THREAD

**Issue by kptlronyttcna** [adamint/spotify-web-api-kotlin#129]
Is it possible to use a http proxy for requests?

**Comment by molikuner** [comment]
As the library, that is used to make requests, supports HTTP proxy usage, it should not be a problem to add such a feature. But currently it isn't possible to setup a HTTP proxy in the library.

**Comment by kptlronyttcna** [comment]
I checked out the source code. NetHttpTransport says use `http://docs.oracle.com/javase/7/docs/api/java/net/doc-files/net-properties.html` for proxy settings. The constructor with proxy param is private. Anyway, this solves my problem.

**Comment by adamint** [comment]
I'd like to look into adding support for setting up a global proxy for requests. This will likely necessitate giving users more control over different aspects of the actual http requests
