### ISSUE TITLE
make /users/{user_id}/playlists throw exception when user doesn't exist

### ISSUE THREAD

**Issue by adamint** [adamint/spotify-web-api-kotlin#13]
This causes unexpected results. There's no good way atm to verify where it's a valid request unless we call getUser to verify... which I really don't want to do (for obvious reasons).

See https://github.com/spotify/web-api/issues/1077

**Comment by adamint** [comment]
this isn't going to be resolved anytime soon by Spotify. documentation is added to warn users

**Comment by adamint** [comment]
Spotify will be fixing this after the new year - the issue will be kept open until then

**Comment by molikuner** [comment]
> Spotify will be fixing this after the new year - the issue will be kept open until then

open? :smile:

**Comment by adamint** [comment]
oh damn :joy: didn't mean for this to be closed
