### ISSUE TITLE
shadowing functions in public and client api

### ISSUE THREAD

**Issue by molikuner** [adamint/spotify-web-api-kotlin#172]
**Describe the bug**
For example `ClientPlaylistApi` and `PlaylistApi` both have a function `getPlaylist` they accept both a single string as argument. The compiler and IDE doesn't complain, as the names are different and `PlaylistApi`s implementation has an optional extra argument...

**To Reproduce**
Look at the definition

**Expected behavior**
Make the difference clear

**Possible solution**
Make functions in `ClientPlaylistApi` include `Client` so there is a difference in name and meaning is clarified.
e. g. `ClientPlaylistApi.getPlaylist(String)` will get `ClientPlaylistApi.getClientPlaylist(String)`

**Further investigation is needed! This is just one example I spotted because I got unexpected behavior!**

**Comment by adamint** [comment]
Renaming client methods to be suffixed with Client seems to be the simplest solution.
