### ISSUE TITLE
When using methods that retrieve multiple paging objects, set limit to 50 if limit is not explicitly set already

### ISSUE THREAD

**Issue by adamint** [adamint/spotify-web-api-kotlin#182]

**Comment by adamint** [comment]
@molikuner not sure exactly how to implement this. any thoughts?

**Comment by molikuner** [comment]
I would change the default argument in the functions from `null` to a new property from the api. This could be default to 50 and be modified by the user in the builder:
```Kotlin
fun getUserPlaylists(
    user: String,
    limit: Int? = this.api.defaultLimit,
    offset: Int? = null
): SpotifyRestActionPaging<Simple Playlist, PagingObject<SimplePlaylist>>
```
As a side note: I would keep the nullability of the limit to allow the user to set this limit to the default of the Spotify Web API.

**Comment by adamint** [comment]
Good, simple idea. I'll work on this early next week.
