### ISSUE TITLE
Support updating the implicit grant token

### ISSUE THREAD

**Issue by chuck-stein** [adamint/spotify-web-api-kotlin#192]
I'm using Spotify Auth SDK to get an implicit grant token (because I do not have a server for the refreshable authorization code flow), and would like an easy way to update a SpotifyClientApi's tokenString once the current token expires and I have a new one from running the auth SDK again. Currently I have to either reinstantiate the SpotifyClientApi every hour or modify it's Token's tokenString field directly.

Ideally, there would be something like a method updateToken on the SpotifyClientApi that takes in a new token string and modifies its Token accordingly.

Thanks!

**Comment by adamint** [comment]
Thanks for opening the issue. This can be added!
(it'll be part of a broader auth overhaul to make the API easier to instantiate and use)

Assigning myself to the issue. We should have the next release before 4/22.

**Comment by adamint** [comment]
@chuck-stein Apologies for the delay! This feature is in #196, which is going to be released as 3.1.0-rc.1 tomorrow

**Comment by chuck-stein** [comment]
@adamint No worries at all, it's not a blocker for my app. Thanks for including the feature!
