### ISSUE TITLE
Add endpoints for authenticated clients (using Authorization Code flow)

### ISSUE THREAD

**Issue by adamint** [adamint/spotify-web-api-kotlin#2]
- [ ] User Library
- [x] Automatically refreshing client token
- [x] Personalization
- [ ] Following
- [x] Profiles
- [ ] Player

Use [the spotify documentation](https://developer.spotify.com/web-api/endpoint-reference/) to view the respective categories. 

To avoid type erasing, it could be necessary to define a new data class.
You need a registered Spotify application to be able to test.

**Comment by adamint** [comment]
Open for Hacktoberfest, welcoming contributions

**Comment by adamint** [comment]
I'm still looking for someone to help with this

**Comment by rachidbm** [comment]
I played around with this library and it worked pretty well, nice! Is there already work done on this issue? I'm particularly interested in creating playlists. 

Other thing is that I checkout the master branch, but it won't build. It refers to ClientLibraryAPI, but that class does not exist...

**Comment by adamint** [comment]
Hey @rachidbm, thanks for the feedback! I'm planning on resolving this issue by Monday night, but the structure is going to change pretty drastically. The issue with the ClientLibraryAPI was a test case I was running to test it before getting rid of the class (temporarily). I never removed the reference.

**Comment by adamint** [comment]
I will be working on this today
