### ISSUE TITLE
Add PKCE Auth Support

### ISSUE THREAD

**Issue by mediaController** [adamint/spotify-web-api-kotlin#203]
Spotify recently added a fourth way to do authorization:

https://developer.spotify.com/community/news/2020/06/18/pkce-oauth/

**Comment by adamint** [comment]
Huh, interesting. Thanks for the heads up. This should not be very difficult to implement. I’ll assign myself.

**Comment by adamint** [comment]
ack - release 7/24

**Comment by Computr0n** [comment]
Is this in a branch?

**Comment by adamint** [comment]
yes it is @Computr0n in a local branch
I’ll push it to origin. 

Accidentally put the deadline as 8/24 instead of 7/24 on my calendar 🙂 sorry about that!

**Comment by adamint** [comment]
[Branch](/adamint/spotify-web-api-kotlin/tree/feature/pkce-auth)

**Comment by adamint** [comment]
Released with the above PR in 3.2.01. Sorry for the late release! Thank you @mediaController for reporting this.
