### ISSUE TITLE
Fix market by country

### ISSUE THREAD

**Issue by Zevsus** [adamint/spotify-web-api-kotlin#214]
EndpointBuilder("/browse/categories").with("limit", limit).with("offset", offset).with(
                            "market",
                            market?.name).
https://developer.spotify.com/console/get-browse-categories/

**Comment by adamint** [comment]
I don't understand what you mean. market is country here

**Comment by Zevsus** [comment]
EndpointBuilder("/browse/categories").with("limit", limit).with("offset", offset).with(
                        "country",
                        market?.name).
Change   "market" - "country"

**Comment by Zevsus** [comment]
It is desirable to change it everywhere
