### ISSUE TITLE
switch to a faster JSON parser

### ISSUE THREAD

**Issue by adamint** [adamint/spotify-web-api-kotlin#22]
I dislike Gson's performance and many of the applications that can implement this library will already be using Jackson. We actually have a few good options, mainly

1) Use Jackson
2) Manually map each JSONObject to its respective class

**Comment by molikuner** [comment]
What do you think about [kotlinx.serialization](https://github.com/Kotlin/kotlinx.serialization)?

**Comment by adamint** [comment]
Interesting 🤔 I didn't realize kotlinx.serialization wasn't experimental anymore. That seems like the best option IMO. May checkout a local branch to mess around with it & compare the jar size & speed to Gson

**Comment by adamint** [comment]
So the weird thing about switching to kt.serialization is that it's really shown that Spotify likes to add *extra* data

**Comment by adamint** [comment]
Getting rid of a lot of legacy code 😎

**Comment by adamint** [comment]
Wow. It looks like Gson is perfectly happy instantiating kotlin objects and placing null as their backing field (completely ignoring null-safety).
