### ISSUE TITLE
When requesting a track everything returns null

### ISSUE THREAD

**Issue by brys0** [adamint/spotify-web-api-kotlin#226]
**Describe the bug**
One day I woke up tried to get a Spotify track name and it returned null after some father digging and nothing found i come here for my issue

**To Reproduce**
1. Request any track on Spotify
2. Try and get the name and other info
3. Returns null

**Expected behavior**
It should give me the entire track model information and track name without giving me null values

**Screenshots**
https://i.imgur.com/1FOt8sZ.png

**Additional context**
Just decided to break one day keep in mind this was after Spotify data breach but friends work fine I will a complete gradle cache wipe and reset to see if the solves it.

**Comment by adamint** [comment]
@brys0 is this still an issue? I am getting no such error.

**Comment by brys0** [comment]
Sorry it was to do with the ?si= header on the url of the spotify track i just fixed it by also taking out the ?si= data and header

**Comment by adamint** [comment]
Gotcha, that would do it! Though it would be easy to strip out query strings in given URLs, they are not allowed to avoid any confusion.

Please let me know if run into any other issues, and feel free to watch this repo if you're interested in keeping up with changes. I'm going to close this issue.

**Comment by brys0** [comment]
Nope thank you a bunch :)
