### ISSUE TITLE
Get recently played not working when there's no data

### ISSUE THREAD

**Issue by duberton** [adamint/spotify-web-api-kotlin#246]
Whenever i perform a call to `spotifyClientApi.player.getRecentlyPlayed` and it returns no data, it fails to deserialize the Json to CursorBasedPagingObject at the exension function `Serializationutils.kt:String.toCursorBasedPagingObject:191`:

Content from the response:
```
{
  "items" : [ ],
  "next" : null,
  "cursors" : null,
  "limit" : 50,
  "href" : "https://api.spotify.com/v1/me/player/recently-played?after=1611402105401&limit=50"
}
```

I guess that's due to 'cursors', it isn't nullable.

Dependency def: `com.adamratzman:spotify-api-kotlin-core:3.4.03`

**Comment by duberton** [comment]
Just confirmed that the issue is in the cursor property: during runtime, while debugging, i put a value for cursor and it was successfully deserialized.

**Comment by adamint** [comment]
I was unaware that cursors had become a nullable property. Thank you

**Comment by duberton** [comment]
Thanks for the quick fix Adam. I appreciate.

**Comment by adamint** [comment]
You're welcome! 3.5.03 should be available in a few hours.

**Comment by adamint** [comment]
@duberton `com.adamratzman:spotify-api-kotlin-core:3.5.03` is now available.

**Comment by duberton** [comment]
Awesome. Thanks a lot!

**Comment by duberton** [comment]
I've validated within my app. Working fine!

**Comment by adamint** [comment]
Great! Please report any other issues you run into. Glad I could push out a fix this soon
