### ISSUE TITLE
Error getting PKCE Client from SpotifyDefaultCredentialStore

### ISSUE THREAD

**Issue by rbbl-dev** [adamint/spotify-web-api-kotlin#266]
**Describe the bug**
`SpotifyDefaultCredentialStore.getSpotifyClientPkceApi#onSuccess` is not getting called

**To Reproduce**
1. checkout https://github.com/rbbl-dev/SpotifyPKCEError
2. set breakpoint in `MainActivity.initializeSpotifyApi`
3. run
4. onSuccess in `initializeSpotifyApi` never gets called

**Expected behavior**
should get called with a proper ClientApi instance

**Smartphone (please complete the following information):**
 - Device: Galaxy A7 2018
 - OS: Android 10
 - Browser: Firefox
 - Wrapper version 3.6.0

**Comment by adamint** [comment]
Continuation on that method is never called... unsure why
