### ISSUE TITLE
iOS Target

### ISSUE THREAD

**Issue by andb3** [adamint/spotify-web-api-kotlin#271]
I'm making a Kotlin Multiplatform app that relies on spotify-web-api-kotlin, and would like to have an iOS target. I'm not sure how much platform-specific code would be needed, so understandable if it's too big a project to add on right now, but hopefully it'll be on the radar for some future release.

**Comment by andb3** [comment]
Thanks!

**Comment by adamint** [comment]
@andb3 this is being released starting `3.6.03`, which is currently syncing to Maven Central (so in a few hours)
