### ISSUE TITLE
Implement Request Caching

### ISSUE THREAD

**Issue by adamint** [adamint/spotify-web-api-kotlin#29]
(this should be very simple)

**Comment by adamint** [comment]
ok this is extremely annoying to test

**Comment by adamint** [comment]
@molikuner If you don't mind, I'd like someone else reviewing/testing my cache implementation (because if something goes wrong with requesting, that endpoint object can't be used). Would you be able to pull the changes and review it?

**Comment by molikuner** [comment]
Yes I'll look over it.

**Comment by molikuner** [comment]
Shouldn't we give the user an option to disable caching?

**Comment by adamint** [comment]
Yeah, we should

**Comment by adamint** [comment]
Added

**Comment by adamint** [comment]
Though I'm really not sure why you'd want to disable caching
