### ISSUE TITLE
Readme code examples outdated?

### ISSUE THREAD

**Issue by ackmanx** [adamint/spotify-web-api-kotlin#301]
**Describe the bug**
I'm seeing `SpotifyApiOptionsBuilder` in the readme, yet this doesn't appear to be a class that's available and Intellij is throwing errors if I try to reference it. Was it removed? I'm a Kotlin novice coming from the JavaScript world, so apologies if this has an obvious answer.

I'm struggling to implement authorization based on the examples provided.

**Desktop (please complete the following information):**
 - OS: Backend Kotlin application using Ktor
 - Version: 3.8.4

**Additional context**

**Comment by adamint** [comment]
Thank you for pointing out the deficiency in this documentation - it has been updated. Indeed, `SpotifyApiOptionsBuilder` has been removed in favor of the `SpotifyAppApiBuilder`, which you can see demonstrated below! The relevant documentation is also located [here](https://adamint.github.io/spotify-web-api-kotlin-docs/spotify-web-api-kotlin/com.adamratzman.spotify/spotify-app-api.html?query=fun%20spotifyAppApi(block:%20SpotifyAppApiBuilder.()%20-%3E%20Unit):%20SpotifyAppApiBuilder). Please let me know if this does not resolve your issue.

```kotlin
val api = spotifyAppApi(
  "clientId",
  "clientSecret",
  token
) { 
  automaticRefresh = false 
}.build()
```


I apologize for the 2-week response time.
