### ISSUE TITLE
Releases >3.8.0 missing iosarm64 on Maven

### ISSUE THREAD

**Issue by jlnstrk** [adamint/spotify-web-api-kotlin#316]
It appears that since 3.8.0, no iosarm64 targets have made it to Maven.
This hinders the use of the generic ios source set with newer versions.

Since I don't see it being explicitly excluded in the build.gradle, I assume this is not on purpose?

**Comment by adamint** [comment]
Thank you for filing this. I will confirm your findings and then release a new minor version with iosarm64 targeting

**Comment by adamint** [comment]
Yep, confirmed this. I'll be creating a release with the arm targets
