### ISSUE TITLE
Implicit authentication error

### ISSUE THREAD

**Issue by BobbyESP** [adamint/spotify-web-api-kotlin#318]
**Describe the bug**
When trying to do Implicit login, an error saying "AUTHENTICATION_SERVICE_UNAVAILABLE" appears. In Spotify's Android example works, but in mine no. I don't really know the reason. I'm passing all the values necessaries and also imported all the activities in the manifest.

**To Reproduce**
1.  Try to make Implicit login with the version 3.8.8 of the library
2.  Authentication fails

**Expected behavior**
Login 

**Screenshots**

https://user-images.githubusercontent.com/60316747/202580355-1f51ba5f-c75d-461c-9d7a-c68910e720c0.mp4

**Desktop (please complete the following information):**
 - OS: [Windows 11]
 - Browser [Brave]
 - Version [1.45.127]

**Smartphone (please complete the following information):**
 - Device: [Xioami 11T Pro]
 - OS: [MIUI 13.0.16 EEA]
 - Browser [Chrome]
 - Version [107]

**Additional context**
The logcat says this things.

I/com.spotify.sdk.android.auth.LoginActivity: Spotify auth completing. The response is in EXTRA with key 'response'
I/spotify-web-api-kotlin: Got implicit auth response of error
I/spotify-web-api-kotlin: Got error in authorization... executing error handler

**Comment by adamint** [comment]
Investigating. I'll update with results

**Comment by BobbyESP** [comment]
Fixed, thanks for your time. The error was that I just putted the SHA1 release key and not the debug one
