### ISSUE TITLE
Missing mavenCentral urls

### ISSUE THREAD

**Issue by rnitame** [adamint/spotify-web-api-kotlin#321]
**Describe the bug**

![image](https://user-images.githubusercontent.com/4950792/212459611-e05ec1b9-e549-4ac9-8d8c-e1ea7db6e705.png)

![image](https://user-images.githubusercontent.com/4950792/212459822-d0007a53-8762-41ff-bba7-104e4ec69685.png)

https://repo.maven.apache.org/maven2/com/adamratzman/spotify-api-kotlin-iosarm64/4.0.0/spotify-api-kotlin-iosarm64-4.0.0.pom is correct.

**To Reproduce**
`gradle/libs.versions.toml` 

```
[versions]
spotify = "4.0.0"

[libraries]
spotify-api-kotlin = { module = "com.adamratzman:spotify-api-kotlin-core", version.ref = "spotify" }
```

Sync project.

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by adamint** [comment]
Hi, are you still encountering this issue? @rnitame

**Comment by jlnstrk** [comment]
Hi! I am. Gradle goes looking for `spotify-web-api-kotlin-<target>` artifacts even though they're actually under `spotify-api-kotlin-<target>`.

See targets' apiElements `availableAt` field [here](https://repo.maven.apache.org/maven2/com/adamratzman/spotify-api-kotlin-core/4.0.0/spotify-api-kotlin-core-4.0.0.module).

For example, for `iosArm64ApiElements` should point to:
https://repo.maven.apache.org/maven2/com/adamratzman/spotify-api-kotlin-iosarm64/4.0.0/

But actually points to:
https://repo.maven.apache.org/maven2/com/adamratzman/spotify-web-api-kotlin-iosarm64/4.0.0/

**Comment by danielholmberg** [comment]
Getting the same issue

`A problem occurred configuring project ':shared'.
> Could not resolve all dependencies for configuration ':shared:iosArm64CompileKlibraries'.
   > Could not find com.adamratzman:spotify-web-api-kotlin-iosarm64:4.0.0.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/com/adamratzman/spotify-web-api-kotlin-iosarm64/4.0.0/spotify-web-api-kotlin-iosarm64-4.0.0.pom
       - https://repo.maven.apache.org/maven2/com/adamratzman/spotify-web-api-kotlin-iosarm64/4.0.0/spotify-web-api-kotlin-iosarm64-4.0.0.pom
       - https://maven.pkg.jetbrains.space/public/p/compose/dev/com/adamratzman/spotify-web-api-kotlin-iosarm64/4.0.0/spotify-web-api-kotlin-iosarm64-4.0.0.pom
     Required by:
         project :shared > com.adamratzman:spotify-api-kotlin-core:4.0.0`

**Comment by Niach** [comment]
+1

**Comment by adamint** [comment]
Hi all, apologies for not getting back to this. Let me take a look
