### ISSUE TITLE
Build failing because of PKCE and Implicit layouts

### ISSUE THREAD

**Issue by BobbyESP** [adamint/spotify-web-api-kotlin#323]
**Describe the bug**
When trying to build the app with the version 4.0.0 of the library, the build fails with AAPT errors

**To Reproduce**
1. Add the version 4.0.0 of the library to the build.gradle file in an Android project
2. Try to build the app
3. See the errors

**Expected behavior**
I wanted the app to build successfully

**Screenshots**
<img width="1802" alt="image" src="https://user-images.githubusercontent.com/60316747/222845315-f1dcb25e-456d-4fae-bf89-66d32e3b9572.png">
<img width="440" alt="image" src="https://user-images.githubusercontent.com/60316747/222845684-4c89cf3b-6c7b-4030-b825-515dc490550d.png">

**Desktop (please complete the following information):**
 - OS: [Windows 11]
 - Browser [Brave]
 - Version [22H2 // 22621.1265]

**Smartphone (please complete the following information):**
 - Device: [Xiaomi 11T Pro]
 - OS: [MIUI 13 // Android 12]
 - Browser [Chrome]
 - Version [12]

**Additional context**
It's for my [Spowlo](https://github.com/BobbyESP/Spowlo) app, you can see in there the source code

**Comment by adamint** [comment]
Hi @BobbyESP, can you share your build.gradle.kts? How are you referencing this library?

**Comment by BobbyESP** [comment]
Hi! Thank you for the answer! If you still need the build.gradle.kts tell mell and I sent it to you! By the way you can see it the the repo that I left in the additional context :)

**Comment by BobbyESP** [comment]
Any updates on this?

**Comment by BobbyESP** [comment]
<img width="634" alt="image" src="https://github.com/adamint/spotify-web-api-kotlin/assets/60316747/15b9ba90-b50d-4b88-af44-d6cc180a8b25">

This should fix the issue

**Comment by adamint** [comment]
Closing with 4.0.1 release. Please try!

**Comment by Lightningtow** [comment]
Unfortunately, whatever changed with 4.0.1 didn't do the trick. Fails to build with both `spotify-api-kotlin-android:4.0.1` and `spotify-api-kotlin-core:4.0.1`.
![image](https://github.com/adamint/spotify-web-api-kotlin/assets/20070994/499cd5f5-643b-44c7-9a23-2405adb11e0f)

**Comment by adamint** [comment]
Ugh, thanks for checking. Sorry @Lightningtow. I'll just remove temporarily the content and allow user-set loading content, and will ping when a new release is out in a few hours.

**Comment by Lightningtow** [comment]
@adamint sounds good, thank you!

**Comment by adamint** [comment]
I've had a lot of problems with this progress bar library, so thought it might be best to remove and allow people who want a loading animation to insert it themselves!

@Lightningtow this should work now. 4.0.2 is in sync now, not sure if you're able to access it at the moment or will need to wait a few hours for maven central sync

**Comment by BobbyESP** [comment]
Thank you guys for helping fix the probldm!
