### ISSUE TITLE
Documentation of the API & helper objects, like paging objects

### ISSUE THREAD

**Issue by adamint** [adamint/spotify-web-api-kotlin#39]
This is incomplete and needs to be done in the near future

**Comment by molikuner** [comment]
The documentation could be generated [automatically](https://github.com/Kotlin/dokka) from the code. This would have the advantage that documentation could also be found in the code at the same time.

**Comment by adamint** [comment]
@molikuner hmm.. maybe with github-flavored markdown?

**Comment by molikuner** [comment]
Yeah using it like this:
```
dokka {
    outputFormat = 'gfm'
    outputDirectory = 'docs/md'
    //includeNonPublic = true
}
```
Works great for Github :wink:

**Comment by adamint** [comment]
Great! I'll put that in
