### ISSUE TITLE
`refresh_token` is overwritten on refresh

### ISSUE THREAD

**Issue by molikuner** [adamint/spotify-web-api-kotlin#41]
I'm getting:
```
com.adamratzman.spotify.utils.BadRequestException: Received Status Code 401. Error cause: Invalid access token
        at com.adamratzman.spotify.utils.SpotifyEndpoint.handleResponse(Endpoints.kt:98)
        at com.adamratzman.spotify.utils.SpotifyEndpoint.execute(Endpoints.kt:59)
       ...
```
Even though I got:
```
Spotify Logger Info: Successfully refreshed the Spotify token                                                                                                                         
```

I'll take a look at it though it's hard to debug because of the time for refresh.

**Comment by molikuner** [comment]
Okay, that didn't take that long :smile:. The problem was that the token is overwritten and the `refresh_token` is deleted because the answer does not contain any. The next time the answer is not `null`, but is, it probably has no valid token. The PR comes.

**Comment by adamint** [comment]
Hmm ok
