### ISSUE TITLE
Better way to deal with PagingObjects

### ISSUE THREAD

**Issue by adamint** [adamint/spotify-web-api-kotlin#43]
We need to further expose a way to generate a sequence when retrieving all linked objects for AbstractPagingObjects. This is made a lot easier by #40

**Comment by adamint** [comment]
Currently, you're able to `getAllItems`, but that's blocking and not ideal, and it's not exactly the most friendly thing to use. Might consider an overloaded function that accepts a consumer. It would have to work like this:
- Calculate the first offset
- Return a dynamic sequence (maybe wrapped to add a check for if it's the last page) whose elements are retrieved through the url generated from the prevent element

**Comment by molikuner** [comment]
Maybe we could expose a way to retreave the items using a Flow or Channel. I would prefer Flow, as it doesn't rely on the user to close it.

**Comment by Computr0n** [comment]
Great work on the library so far!

I have a question, what is going on here:

```kotlin
    /**
     * Flow the paging objects.
     * */
    @JvmOverloads
    @ExperimentalCoroutinesApi
    fun flowPagingObjects(context: CoroutineContext = Dispatchers.Default): Flow<AbstractPagingObject<Z>> =
        flow<AbstractPagingObject<Z>> {
            complete().also { master ->
                emitAll(master.flowBackward())
                emit(master)
                emitAll(master.flowForward())
            }
        }.flowOn(context)
```

why is there a call to complete, which runsBlocking?

```kotlin
    fun complete(): T = runBlocking {
        suspendComplete()
    }
```

couldn't it just call the inner suspendQueue() directly and then this whole thing would be asynchronous?

```kotlin
    suspend fun suspendComplete(context: CoroutineContext = Dispatchers.Default): T = withContext(context) {
        hasRunBacking = true
        return@withContext try {
            supplier().also { hasCompletedBacking = true }
        } catch (e: CancellationException) {
            throw e
        } catch (e: Throwable) {
            throw e
        }
    }

```

With the way it is currently anything that starts collecting the flow will have to block the thread until the one SpotifyRestAction completes 

Am I missing something..?
Why is it necessary for the library to runBlocking { } anything? 
Couldn't this be left up to the consumers of the library methods?

**Comment by molikuner** [comment]
@ComputrOn Looks like we missed that one when refactoring this lib to be more async. Indeed this should be `suspendComplete()`. Feel free to open a PR.

**Comment by adamint** [comment]
3.0.0 will be ready to be released after this is resolved.
