### ISSUE TITLE
Deleting tracks from playlists issue

### ISSUE THREAD

**Issue by adamint** [adamint/spotify-web-api-kotlin#6]
Been trying to implement [track deletion](https://beta.developer.spotify.com/documentation/web-api/reference/playlists/remove-tracks-playlist/) yet keep running into 400 errors. Would appreciate if anyone would be able to contribute

**Comment by molikuner** [comment]
having this problem:
```Cannot set a request body for HTTP method DELETE```

how did you solved it?

**Comment by molikuner** [comment]
I looked into it. It's a problem of jsoup. It isn't permitted to do http DELETE requests with a request body.
I didn't tested :

URL(apiEndpoint).openConnection()



yet, which would use the basic http request api of Java. Maybe I'll rewrite the execute/request function to use it instead of jsoup.
Would that be okay?

**Comment by adamint** [comment]
To be frank, I'd prefer to use an existing HTTP library like OkHttp if we have to change how requests are made. Thoughts?

**Comment by molikuner** [comment]
I've never worked with OkHttp before, but it's worth a try. I'll present my results from testing. Today I don't have so much time, so maybe tomorrow.

**Comment by molikuner** [comment]
Now it's working, but to keep dependencies low it would be good to also replace the other functions. I couldn't get the refresh_token function to work. I pushed my code as command. Basicly OkHttp doesn't allow the
```
x-www-form-urlencoded
```
MediaType because it doesn't fit a MutlipartBody. Spotify gives a
```
415
```
when using the wrong MediaType. Do you know any way to do such a request with OkHttp?

**Comment by adamint** [comment]
> Now it's working, but to keep dependencies low it would be good to also replace the other functions. I couldn't get the refresh_token function to work. I pushed my code as command. Basicly OkHttp doesn't allow the `x-www-form-urlencoded` MediaType because it doesn't fit a MutlipartBody. Spotify gives a `415` when using the wrong MediaType. Do you know any way to do such a request with OkHttp?

I do not, unfortunately. I can look into it in the next few days

**Comment by adamint** [comment]
@molikuner do you still have interest in doing this?

**Comment by molikuner** [comment]
@adamint yes, hadn't time yet to look into it but I'm interested. Do you have a solution?

**Comment by molikuner** [comment]
The usage of the new Until functions to create URIs need to be reviewed. I thought it would be good to be able to pass a URI instead of the ID and the API should handle it. But I added it sometimes without testing and it isn't added consistently.

**Comment by adamint** [comment]
What do you mean by the `Until` functions? I'm just a little confused by what you mean.

**Comment by molikuner** [comment]
[those extension functions](https://github.com/molikuner/spotify-web-api-kotlin/blob/master/src/main/kotlin/com/adamratzman/spotify/utils/SpotifyUri.kt)  
They can be used to be sure the ID is an ID in the request or that the URI is an URI in the request.

**Comment by adamint** [comment]
ah okay, I completely missed that addition. I'm rewriting the tests to be - you know - not kiddy tests, so I'll look through them and add them to the util tests.

**Comment by adamint** [comment]
I've been doing major refractoring inside the [dev branch](https://github.com/adamint/spotify-web-api-kotlin/tree/dev). If you'd like, you can checkout that branch and help port your changes over. Otherwise, I can do it in a few hours. I hope to focus more on test-driven development during this rewrite, so if you do, tests are a must.

Next, I have to retroactively add tests for nearly all the existing functions, which will take a while. After that (or if you want, you can get a head start on it), I'll be wrapping `HttpsURLConnection`. I feel like the extra size isn't worth writing an extra 50 or so lines of code.

**Comment by molikuner** [comment]
Yes indeed. I searched a little bit.
Jsoup defines there request methods with a attribute if they can have a [body](https://github.com/jhy/jsoup/blob/master/src/main/java/org/jsoup/Connection.java#L34). They [check](https://github.com/jhy/jsoup/blob/master/src/main/java/org/jsoup/helper/HttpConnection.java#L713) it before requesting. Actually by viewing the code now, I do not understand why there isn't an exception thrown, but anyways this is probably the answer why the endpoint always return with an error.

**Comment by adamint** [comment]
Yeah I saw that. Pretty sure it’s because we ignore http errors

**Comment by adamint** [comment]
I'm like 80% sure this works as intended but I never finished writing tests. Oops
